// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolPlatform.Api.Data;

#nullable disable

namespace SchoolPlatform.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260212024203_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolPlatform.Api.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GradeLevel")
                        .HasColumnType("int");

                    b.HasKey("StudentId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("SchoolPlatform.Api.Models.StudentBehaviorPrediction", b =>
                {
                    b.Property<int>("PredictionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PredictionId"));

                    b.Property<int>("ClusterId")
                        .HasColumnType("int");

                    b.Property<string>("ClusterLabel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MetricId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PredictedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("PredictionId");

                    b.HasIndex("MetricId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentBehaviorPredictions");
                });

            modelBuilder.Entity("SchoolPlatform.Api.Models.StudentMetric", b =>
                {
                    b.Property<int>("MetricId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MetricId"));

                    b.Property<double>("Age")
                        .HasColumnType("float");

                    b.Property<double>("AssignmentCompletion")
                        .HasColumnType("float");

                    b.Property<double>("Attendance")
                        .HasColumnType("float");

                    b.Property<double>("Discussions")
                        .HasColumnType("float");

                    b.Property<double>("EduTech")
                        .HasColumnType("float");

                    b.Property<double>("ExamScore")
                        .HasColumnType("float");

                    b.Property<double>("Extracurricular")
                        .HasColumnType("float");

                    b.Property<double>("FinalGrade")
                        .HasColumnType("float");

                    b.Property<double>("Internet")
                        .HasColumnType("float");

                    b.Property<double>("Motivation")
                        .HasColumnType("float");

                    b.Property<double>("OnlineCourses")
                        .HasColumnType("float");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Resources")
                        .HasColumnType("float");

                    b.Property<double>("StressLevel")
                        .HasColumnType("float");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<double>("StudyHours")
                        .HasColumnType("float");

                    b.HasKey("MetricId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentMetrics");
                });

            modelBuilder.Entity("SchoolPlatform.Api.Models.Teacher", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeacherId");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("SchoolPlatform.Api.Models.TeacherStudent", b =>
                {
                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("TeacherId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("TeacherStudents");
                });

            modelBuilder.Entity("SchoolPlatform.Api.Models.StudentBehaviorPrediction", b =>
                {
                    b.HasOne("SchoolPlatform.Api.Models.StudentMetric", "Metric")
                        .WithMany()
                        .HasForeignKey("MetricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolPlatform.Api.Models.Student", "Student")
                        .WithMany("Predictions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Metric");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolPlatform.Api.Models.StudentMetric", b =>
                {
                    b.HasOne("SchoolPlatform.Api.Models.Student", "Student")
                        .WithMany("Metrics")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolPlatform.Api.Models.TeacherStudent", b =>
                {
                    b.HasOne("SchoolPlatform.Api.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolPlatform.Api.Models.Teacher", "Teacher")
                        .WithMany("TeacherStudents")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SchoolPlatform.Api.Models.Student", b =>
                {
                    b.Navigation("Metrics");

                    b.Navigation("Predictions");
                });

            modelBuilder.Entity("SchoolPlatform.Api.Models.Teacher", b =>
                {
                    b.Navigation("TeacherStudents");
                });
#pragma warning restore 612, 618
        }
    }
}
